### ISSUE TITLE
TaskOperations.createTasks does not release lock in some scenarios

### ISSUE THREAD

**Issue by JaywenFan** [Azure/azure-batch-sdk-for-java#27]
Hi,

When we continuously executing batch tasks by calling createTasks, lock is not released in a call and then block the thread.

Stack like this:

        at com.microsoft.azure.batch.TaskOperations.createTasks(TaskOperations.java:256)
        - locked <0x00000006d68b5200> (a java.lang.Object)
        at com.microsoft.azure.batch.TaskOperations.createTasks(TaskOperations.java:93)

Snippet in TaskOperations:

```
            if (taskList.size() > 0) {
                submit_chunk(taskList);
            }

            synchronized (lock) {
                // Notify main thread that sub thread finished
                lock.notify();
            }
```

If some exception throws from _submit_chunk_ and not be caught, will not notify to release lock.

That is a problem, maybe _lock.notify()_ should be surround in **finally** block. Please check, thanks!

**Comment by roweak** [comment]
@xingwu1

**Comment by xingwu1** [comment]
@bgklein Could you look this issue?

**Comment by bgklein** [comment]
Yes I will add this into the next Java SDK update
